# Project information
site_name: Ehoney欺骗防御系统
site_description: www.seccome.com
site_author: licheng
edit_url: 'edit/master/doc/'
docs_dir: 'doc/'
repo_name: 'seccome/Ehoney'
repo_url: 'https://github.com/seccome/Ehoney'

# Configuration
theme:
  name: 'material'
  logo: ''
  favicon: ''
  palette:
    primary: 'white'
  features:
    - navigation.top
    - header.autohide
  language: 'zh'

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/seccome/Ehoney'
 
nav:

  - Home: README.md
  - 介绍:
    - Ehoney: Introduction/Ehoney.md
  - 快速开始:
    - 环境要求: QuickStart/Environment.md
    - 部署安装: QuickStart/Deploy.md
    - 快速使用: QuickStart/Start.md
  - 功能说明: 
    - 蜜罐拓扑: Tutorials/HoneypotTopology.md
    - 蜜罐列表: Tutorials/HoneypotList.md
    - 协议转发: Tutorials/ProtocolForward.md
    - 透明转发: Tutorials/TransparentForward.md
    - 诱捕管理: Tutorials/Support.md
    - 探针列表: Tutorials/ProbeList.md 
    - 攻击日志: Tutorials/AttackLog.md
    - 系统设置: Tutorials/Settings.md
  - 模拟攻击:
    - HTTP: AttackSample/HTTP.md
    - SSH: AttackSample/SSH.md
    - MYSQL: AttackSample/MYSQL.md
    - REDIS: AttackSample/REDIS.md
    - TELNET: AttackSample/TELNET.md
  - 其他:
    - 名字解释: Others/Glossary.md
    - FAQ:      Others/FAQ.md
    - PDF: pdf/Ehoney.pdf
  - 项目仓库: 'https://github.com/seccome/Ehoney'

markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
#      toc_depth: 3
      permalink: true
      separator: "_"
  - mdx_truly_sane_lists
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

static_templates:
  - index.html

# Plugins
plugins:
  - macros
  - git-revision-date-localized
  - with-pdf:
      copyright: 
      cover_subtitle:  
      author:  
      cover: true
      back_cover: true
      cover_logo: './img/logo_ehoney_black.svg'
      output_path: pdf/Ehoney.pdf
      show_anchors: true
      toc_level: 2

extra_javascript:
  - js/version-select.js
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#google_analytics:
#  - UA-12345-78
#  - auto
